name: Daily Make Update

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC.

jobs:
  update:
    runs-on: ubuntu-latest # Ubuntu is generally faster and more cost-efficient for GitHub to run, making it the default choice. For most projects, Linux (Ubuntu) will work just fine even if developed on macOS.

    steps:
      # Step 1: Download the GitHub repository’s source code to the runner (the virtual machine where the action is being executed). Without this step, the subsequent steps wouldn't have access to the repository's code.
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Run 'make update' to update the obsidian repository and push.
      - name: Run make update
        run: make update
